import GraphqlProvider from '@/components/provider-client';
import { ChakraProvider } from '@chakra-ui/react';
import '../styles/globals.css';
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <ChakraProvider>
                    <GraphqlProvider>{children}</GraphqlProvider>
                </ChakraProvider>
            </body>
        </html>
    );
}
