'use client';
import GraphqlProvider from '@/components/provider-client';
import { Breadcrumb, BreadcrumbItem, Center, ChakraProvider, Divider } from '@chakra-ui/react';
import Head from 'next/head';
import Link from 'next/link';
import '../styles/globals.css';
// export const metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
// };
import { MyMachineReactContext } from '@/xstate';
import { WagmiConfig } from 'wagmi';
import { config } from '../Utils/config';

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <ChakraProvider>
                    <GraphqlProvider>
                        <MyMachineReactContext.Provider>
                            <WagmiConfig config={config}>
                                <Head>
                                    <title>Home</title>
                                    <meta name="description" content="Generated by create next app" />
                                    <link rel="icon" href="/favicon.ico" />
                                </Head>

                                <Center className="mt-6">
                                    <Breadcrumb spacing="8px">
                                        <BreadcrumbItem>
                                            <Link href="/" className="underline">
                                                Home
                                            </Link>
                                        </BreadcrumbItem>
                                        <BreadcrumbItem>
                                            <Link href="/users">Users</Link>
                                        </BreadcrumbItem>
                                        <BreadcrumbItem>
                                            <Link href="/bill">Bills</Link>
                                        </BreadcrumbItem>
                                        <BreadcrumbItem>
                                            <Link href="/todolist">Todo-list</Link>
                                        </BreadcrumbItem>
                                    </Breadcrumb>
                                </Center>

                                <Center height="50px">
                                    <Divider />
                                </Center>

                                <main>{children}</main>

                                <Center height="50px">
                                    <Divider />
                                </Center>

                                <footer></footer>
                            </WagmiConfig>
                        </MyMachineReactContext.Provider>
                    </GraphqlProvider>
                </ChakraProvider>
            </body>
        </html>
    );
}
