import { Center, Divider } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const About: NextPage = () => {
    return (
        <div>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Center height="50px">
                <nav>
                    <Link href="/">Home</Link>
                </nav>
            </Center>

            <Center height="50px">
                <Divider />
            </Center>

            <main>
                <Center height="50px">
                    <h1>Welcome to the About page</h1>
                </Center>
            </main>

            <Center height="50px">
                <Divider />
            </Center>

            <footer></footer>
        </div>
    );
};

export default About;
