import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, Center, Divider } from '@chakra-ui/react';
import { ChevronRightIcon } from '@chakra-ui/icons';
const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Center className="mt-6">
                <Breadcrumb spacing="8px" separator={<ChevronRightIcon color="gray.500" />}>
                    <BreadcrumbItem>
                        <Link href="/users">Users</Link>
                    </BreadcrumbItem>

                    <BreadcrumbItem>
                        <Link href="/about">About</Link>
                    </BreadcrumbItem>

                    <BreadcrumbItem isCurrentPage>
                        <Link href="#">Home</Link>
                    </BreadcrumbItem>
                </Breadcrumb>
            </Center>

            <Center height="50px">
                <Divider />
            </Center>

            <main>
                <Center height="50px">
                    <h1>Welcome to the Home page</h1>
                </Center>
            </main>

            <Center height="50px">
                <Divider />
            </Center>

            <footer></footer>
        </div>
    );
};

export default Home;
